address/urls.py
from django.urls import path,include   
from rest_framework import routers 
from .views import *

app_name = "address"

urlpatterns  = [
    path('', AddressListView.as_view(), name='address-list'),
    path('add/', AddressCreateView.as_view(), name='address-add'),
    path('<int:pk>/', AddressDetailView.as_view(), name='address-detail'),
    path('<int:pk>/edit/', AddressUpdateView.as_view(), name='address-edit'),
    path('<int:pk>/remove/', AddressDeleteView.as_view(), name='address-remove'),
]

propertymanagement/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import  views as homeViews
from . import views
from django.views.generic import TemplateView


urlpatterns = [
    
    path('',homeViews.HomeView.as_view(), name="mainpage"),    
    path('contact-us/',homeViews.ContactView.as_view(), name="contactus"),
    path('success/',TemplateView.as_view(template_name='contact_success.html'), name="success"),
    path('about-us/', homeViews.AboutUsView.as_view(),name="about-us"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('address/', include('address.urls')),
    path('rentals/', include('housing.urls')),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/change_password_form.html'),name='password_change'),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(), 
        name='password_change_done'),
    path('accounts/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), 
    name='password_reset_confirm'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        template_name="registration/password_reset_form.html"
    ), name='password_reset'),
    
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

# from django.conf.urls import (
# handler400, handler403, handler404, handler500
# )
# handler404 = homeViews.custom_404
# handler500 = homeViews.custom_500

address/models.py
from django.db import models
from accounts.models import UserProfile, TimestampModel

from django.urls import reverse

# Create your models here.
class Address(TimestampModel):
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    street_address1 = models.CharField(max_length=80)
    street_address2 = models.CharField(max_length=20)
    city = models.CharField(max_length=60, default="Madison")
    state = models.CharField(max_length=30, default="WI")
    zipcode = models.CharField(max_length=10, default="53703")
    country = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Address'
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return '%s %s %s' % (self.street_address1, self.city, self.state)

    def get_absolute_url(self):
        return reverse('address:address-detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('address:address-edit', args=[self.pk])

    def get_delete_url(self):
        return reverse('address:address-remove', kwargs={'pk': self.pk})

address/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse,reverse_lazy
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .models import Address


class RestrictToOwnerMixin(LoginRequiredMixin):

    def get_queryset(self):
        qs = super(RestrictToOwnerMixin, self).get_queryset()
        qs = qs.filter(owner=self.request.user.userprofile)
        return qs


class AddressListView(ListView):
    model = Address
    queryset = Address.objects.all()
    paginate_by = 4
    context_object_name = 'addresses'


class AddressDetailView(DetailView):
    queryset = Address.objects.all()


class AddressCreateView(CreateView):
    model = Address
    fields = ['street_address1', "street_address2", "city","state","zipcode" ,"country" ]
    # context_object_name = 'address'

    def form_valid(self, form):
        form.instance.owner = self.request.user.userprofile
        return super().form_valid(form)
    

class AddressUpdateView(RestrictToOwnerMixin, UpdateView):
    model = Address
    fields = ['street_address1', "street_address2", "city","state","zipcode" ,"country" ]

class AddressDeleteView(RestrictToOwnerMixin, DeleteView):
    model = Address
    # success_url = reverse_lazy('housing:address-list')
    template_name = 'object_confirm_delete.html'

    def get_success_url(self):
        return reverse('address:address-list')


        

address/templates/address/_view_item.html
<div class="row">
	<div class="col-m-3 offset-1">
		<h5 class="gi-sh">Address</h5>
		<p class="nm"> {{object.street_address1}}  {{address.street_address2}}</p>
		<p class="nm"> {{address.city}}</p>
		<p class="nm"> {{address.state|upper}}</p>
		<p class="nm"> {{address.country}}</p>
		<p class="nm"> {{address.zipcode}} </p>
	</div>
</div>

address/templates/address/address_detail.html
{% extends "_base.html"%}
{%block content%}
{# Address Detail#}
<div class="row">
<div class="col-md-6">
<div class="Card">
<h1 class="text-align-cnter">Address Detail</h1>

{% if request.user.is_staff %}
<span class=" btn-group ml-auto"><a class="btn btn-primary" href="{{ address.get_update_url}}">Edit Address</a>
	<a class="btn btn-danger" href="{{object.get_delete_url}}">Delete</a></span>
{% endif %}
	
	
	{% include 'address/_view_item.html' %}
	<a href="{% url 'address:address-list'%}">Back to Address list</a>
</div>
</div>
</div>
{% endblock content %}

address/templates/address/address_form.html
{% extends '_base.html'%}
{% block head_title%} Address {{block.super}}{% endblock head_title %}
{% block content %}
	<div class="row">
		<div class="col-md-6 offset-3">
			<div class="card">
				<div class="card-header"> <h1>Add Address</h1>
				</div>
				<div class="card-body">
					<form action="" method="post" role="form" class="form-horizontal">
					{% csrf_token%}					
						{% include '_fields.html'%}
					
						<div class="form-group">
							<input class="btn btn-primary" type="submit" name="register" value="Save Address">
						</div>
						<p>{{form.non_fields_errors}}</p>
						
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

address/templates/address/address_list.html
{% extends '_base.html' %}

{% block content %}
<h1>Addresses</h1>
<div class="card-group">
        {% for address in object_list %}
        
        <div class="card">
          <div class="card-body">
                <ul class="list-group" >
                        <li class="list-group-item bg-success">{{ address.street_address1}} {{ address.street_address2}}</li>
                        <li class="list-group-item">{{ address.city}}</li>
                        <li class="list-group-item">{{ address.state}}</li>
                    </ul>
                    <span class=" btn-group ml-auto"><a class="btn btn-primary" href="{{ address.get_update_url}}">Edit Address</a>
                        <a class="btn btn-danger" href="{{address.get_delete_url}}">Delete</a></span>
          </div>
          
        </div>
 
        {% endfor %}
</div>
  
    <a  class="btn btn-primary" href="{% url 'address:address-add'%}">Add Address</a>
    {%include 'pagination.html'%}
{% endblock %}