accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import UserRegistrationView, UserProfileDetailView, UserProfileEditView
from  django.urls import reverse_lazy
app_name = 'accounts'
urlpatterns = [    
    path('register', UserRegistrationView.as_view(), name='register'),
    path('login', auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="accounts/logout.html"), name="logout"),
    path('profile/<slug:slug>/',
        UserProfileDetailView.as_view(), name='profile'),
    path('edit-profile/', UserProfileEditView.as_view(), name='update_profile'),
]

address/urls.py
from django.urls import path,include   
from rest_framework import routers 
from .views import *

app_name = "address"

urlpatterns  = [
    path('', AddressListView.as_view(), name='address-list'),
    path('add/', AddressCreateView.as_view(), name='address-add'),
    path('<int:pk>/', AddressDetailView.as_view(), name='address-detail'),
    path('<int:pk>/edit/', AddressUpdateView.as_view(), name='address-edit'),
    path('<int:pk>/remove/', AddressDeleteView.as_view(), name='address-remove'),
]

propertymanagement/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import  views as homeViews
from . import views
from django.views.generic import TemplateView


urlpatterns = [
    
    path('',homeViews.HomeView.as_view(), name="mainpage"),    
    path('contact-us/',homeViews.ContactView.as_view(), name="contactus"),
    path('success/',TemplateView.as_view(template_name='contact_success.html'), name="success"),
    path('about-us/', homeViews.AboutUsView.as_view(),name="about-us"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('address/', include('address.urls')),
    path('rentals/', include('housing.urls')),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/change_password_form.html'),name='password_change'),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(), 
        name='password_change_done'),
    path('accounts/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), 
    name='password_reset_confirm'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        template_name="registration/password_reset_form.html"
    ), name='password_reset'),
    
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

# from django.conf.urls import (
# handler400, handler403, handler404, handler500
# )
# handler404 = homeViews.custom_404
# handler500 = homeViews.custom_500

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.db.models.signals import post_save
from datetime import date

class TimestampModel(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
def get_upload_path(instance, filename):
  return 'img/users/{0}/{1}'.format(instance.user.username, filename)
def avatar_path(instance, filename):
    return "user_{id}/{file}".format(id=instance.user.id, file=filename)

class UserProfile(TimestampModel):
    GENDER_CHOICES = [('M', 'Male'),
                      ('F', 'Female')]
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    biography = models.TextField()
    birthday = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    profile_pic = models.ImageField(
        upload_to=get_upload_path, default='', blank=True)
    profession = models.CharField(max_length=100, blank=True, null=True)

    @property
    def age(self):
        today = date.today()
        if not self.birthday:
            self.birthday = today
        delta = (today.year - self.birthday.year) - ((today.month,
                                                      today.day) < (self.birthday.month, self.birthday.day))
        return delta

    def __str__(self):
        return '{}'.format(self.user)

    def get_absolute_url(self):
        return reverse('accounts:profile', {'slug': self.user.username})


def create_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    middle_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'middle_name',
                  'last_name', 'email', 'password']

accounts/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from django.urls import reverse
from django.views.generic.detail import DetailView 
from django.views.generic.edit import CreateView, UpdateView 

from .forms import UserRegistrationForm
from .models import UserProfile

class RestrictToUserMixin(LoginRequiredMixin):

    def get_queryset(self):
        qs = super(RestrictToUserMixin, self).get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs


class UserRegistrationView(CreateView):
    form_class = UserRegistrationForm
    template_name = 'accounts/accounts_form.html'

    def form_valid(self, form):
        if form.is_valid:
            user = form.save(commit=False)
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user = authenticate(username=username, password=password)
        return super(UserRegistrationView, self).form_valid(form)

    def get_success_url(self):
        return reverse('accounts:login')


class UserProfileDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    slug_field = 'username'
    template_name = 'accounts/userprofile_detail.html'

    def get_object(self, queryset=None):
        user = super(UserProfileDetailView, self).get_object(queryset)
        UserProfile.objects.get_or_create(user=user)
        return user


class UserProfileEditView(UpdateView):
    model = UserProfile
    fields = ['biography', 'birthday', 'gender', 'profile_pic', 'profession']

    def get_object(self, queryset=None):
        return UserProfile.objects.get_or_create(user=self.request.user)[0]

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"slug": self.request.user})

accounts/templates/accounts/accounts_form.html
{% extends '_base.html'%}
{% block head_title%} register {{block.super}}{% endblock head_title %}
{% block content %}
	<div class="row">
		<div class="col-md-8 offset-2">
			<div class="card">
				<div class="card-header"> <h1>User Registration Form</h1>
				</div>
				<div class="card-body">
					<form action="" method="post" role="form" class="form-horizontal">
					{% csrf_token%}					
						{% include '_fields.html'%}
					
						<div class="form-group">
							<input class="btn btn-success" type="submit" name="register" value="Register">
						</div>
						<p>{{form.non_fields_errors}}</p>
						
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends '_base.html' %} {% block head_title%} {{block.super}} | Login {% endblock head_title %} {% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-header">
                <h1>Login</h1>
            </div>
            <div class="card-body">
                {% if form.errors %}
                <p>Your username and password didn't match. Please try again.</p>
                {% endif %}
                <form action="{% url 'accounts:login'%}" method="post" role="form">
                    {% csrf_token%} {% include '_fields.html'%}
                    <div class="form-group row">
                        <div class="col-6 offset-3">
                            <input class="btn btn-success" type="submit" value="Login">
                            <a class="btn btn-outline-secondary" href="{% url 'password_reset'%}">Reset Password</a>
                        </div>
                    </div>
                    <p>{{form.non_fields_errors}}</p>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/logout.html
{% extends '_base.html' %}
{% block head_title %}Logout {{block.super}}{% endblock head_title%}
{% block headline %}
{% endblock headline %}
	{% block content %}
		<div class="row">
			<div class="col-md-6 offset-3">				
				<div class="card">
					<p class="alert alert-success">
						You have been successfully logged out....
					</p>
					<p><a class="btn btn-info" href="{% url 'accounts:login'%}">Log in again</a>
					 No account? <a class="btn btn-info" href="{% url 'accounts:register'%}">Register</a></p>
					 <a class="btn btn-secondary" href="{% url 'mainpage'%}">
						<i class="fas fa-arrow-left fa-2x"></i>
					 <i class="fas fa-home fa-2x"></i> Back Home</a>
					
				</div>
			</div>
		</div>
	{% endblock content%}

accounts/templates/accounts/userprofile_detail.html
{% extends '_base.html'%} {% load static %} {% comment %} {% load avatar_tags %} --> {% endcomment %} {% block head_title%} user profile {{block.super}}{% endblock head_title %} {% block content %} {% if object.username == user.username %}
<div class="row">
    <div class="col-md-6 offset-3">
        <div class="card-header">
            <h1 class="text-center">{{ user.username|capfirst }}'s Profile</h1>
        </div>
        <div class="card d-flex flex-row">

            {% if not user.userprofile.profile_pic %}
            <img class="img-fluid rounded-circle" src="{% static 'img/logor.png' %}" alt="User profile Photo" /> {% else %}
            <img class="img-fluid rounded-circle" src="{{user.userprofile.profile_pic.url}}" alt="User profile Photo" /> {% endif %} {% if user.userprofile %}
            <div class="card-body">
                <h2>Username: {{user.username}}</h2>
                <p class="card-text">First Name: {{ user.first_name }} </p>
                <p class="card-text">Last Name: {{ user.last_name}} </p>
                <p class="card-text">Birth Date: {{user.userprofile.birthday}} </p>
                <p class="card-text"></p>Bio: {{ user.userprofile.biography }} </p>
                {% if user.userprofile.birthday%}
                <p></p>Age: {{user.userprofile.age}}</p>
                {% endif%}
                <p>Gender: {{user.userprofile.get_gender_display}} </p>
                {% endif %}
                <a class="btn btn-outline-primary" href="{%url 'accounts:update_profile'%}">
                    <i class="fas fa-user-edit"></i> Edit profile</a>
            </div>
        </div>



    </div>

    {% comment %}
    <!-- {% avatar user 65 class="img-circle img-responsive" id="user_avatar" %} -->
    {% endcomment %}




</div>
{% endif%} {% endblock content %}

accounts/templates/accounts/userprofile_form.html
{% extends '_base.html'%} {% block head_title%} Edit user profile {{block.super}}{% endblock head_title %} {% block content %}
<div class="row">
    <div class="col-sm-6 offset-2">
        <div class="card card-default">
            <div class="card-header">
                <h1>User Profile Edit Form</h1>
            </div>
            {%if user.username%}
            <div class="card-body">

                <form action="" method="post" role="form" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token%} {% include '_fields.html'%}
                    <div class="form-group">
                        <input class="btn btn-success" type="submit" name="edit_profile" value="Edit Profile">
                    </div>
                    <p>{{form.non_fields_errors}}</p>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}