accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import UserRegistrationView, UserProfileDetailView, UserProfileEditView
from  django.urls import reverse_lazy
app_name = 'accounts'
urlpatterns = [    
    path('register', UserRegistrationView.as_view(), name='register'),
    path('login', auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="accounts/logout.html"), name="logout"),
    path('profile/<slug:slug>/',
        UserProfileDetailView.as_view(), name='profile'),
    path('edit-profile/', UserProfileEditView.as_view(), name='update_profile'),
]

address/urls.py
from django.urls import path,include   
from rest_framework import routers 
from .views import *

app_name = "address"

urlpatterns  = [
    path('', AddressListView.as_view(), name='address-list'),
    path('add/', AddressCreateView.as_view(), name='address-add'),
    path('<int:pk>/', AddressDetailView.as_view(), name='address-detail'),
    path('<int:pk>/edit/', AddressUpdateView.as_view(), name='address-edit'),
    path('<int:pk>/remove/', AddressDeleteView.as_view(), name='address-remove'),
]

housing/urls.py
from django.urls import path, re_path
from rest_framework.urlpatterns import format_suffix_patterns

from .views import *


app_name = 'housing'

urlpatterns = [
    path('categories/', RentalCategoryListView.as_view(), name='category-list'),
    path('category/new/', RentalCategoryCreateView.as_view(), name='category-create'),
    path('category/<slug>/', RentalCategoryDetailView.as_view(), name='category-detail'),
    path('category/<slug>/edit/', RentalCategoryUpdateView.as_view(), name='category-edit'),
    path('category/<slug>/detete/', RentalCategoryDeleteView.as_view(),name='category-remove'),
    
    path('properies/', RentalPropertyListView.as_view(), name='property-list'),
    path('property/add/', RentalPropertyCreateView.as_view(), name='property-create'),
    path('property/<int:pk>/', RentalPropertyDetailView.as_view(), name='property-detail'),
    path('property/<int:pk>/edit/', RentalPropertyUpdateView.as_view(), name='property-edit'),
    path('property/<int:pk>/delete/', RentalPropertyDeleteView.as_view(), name='property-remove'),

]
urlpatterns = format_suffix_patterns(urlpatterns)

propertymanagement/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import  views as homeViews
from . import views
from django.views.generic import TemplateView


urlpatterns = [
    
    path('',homeViews.HomeView.as_view(), name="mainpage"),    
    path('contact-us/',homeViews.ContactView.as_view(), name="contactus"),
    path('success/',TemplateView.as_view(template_name='contact_success.html'), name="success"),
    path('about-us/', homeViews.AboutUsView.as_view(),name="about-us"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('address/', include('address.urls')),
    path('rentals/', include('housing.urls')),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/change_password_form.html'),name='password_change'),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(), 
        name='password_change_done'),
    path('accounts/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), 
    name='password_reset_confirm'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        template_name="registration/password_reset_form.html"
    ), name='password_reset'),
    
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

# from django.conf.urls import (
# handler400, handler403, handler404, handler500
# )
# handler404 = homeViews.custom_404
# handler500 = homeViews.custom_500

templates/_base.html
{% load static %}
<html>

<head>
    {% include "head.html" %}
</head>

<body>
    <a class="skip-main" href="#main">Skip to main content</a>
    <header>
        {% include 'header.html'%}
    </header>
    <main class="container-fuild" id="main">

        {% block content %} {% endblock content%}

    </main>
    {% block footer %} {% include "footer.html" %} {% endblock footer %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>

</html>

templates/_fields.html
{% load extra_css %}
{%for field in form%}
{{field.errors}}
<div class="form-group row">
<label  class=" control-label col-sm-3" for="id_{{label_tag}}">{{field.label_tag}}</label>
<div class="col-sm-9">
{{field|addcss:"form-control"}}	
</div>
</div>
{% endfor%}

templates/about.html
{% extends '_base.html' %}


{% block content %}

<main class="">
        <h1>Housing for everyone</h1>
        
        <p>We do peer matching for all the tenants that lives in shared house.</p>
        <p>The building are fully furnished but tenants can request a head time to have an unfurnished room.</p>
</main>
    
{% endblock content %}
    

templates/contact.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% load bootstrap4 %}

<div class="row">
  <div class="col-md-8 offset-md-2">
      <div class="card">
          <div class="card-header">
    <h1>Contact Us</h1>
  </div>
  <div class="card-body">
<form method="post" class="form" class="card-body">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-success">Send Message</button>
    {% endbuttons %}
</form>
</div>
</div>
</div>
</div>
{% endblock content %}
  

templates/contact_success.html
{% extends '_base.html' %}

{% block content %}
<main class="row">
    <div class="col-md-8 offset-2">
        <div class="alert alert-success">
            <h1>Than you for contacting us!</h1>
            <p>We will get back to you with 24 hours.</p>
        </div>
    </div>
</main>
    
{% endblock content %}
    

templates/footer.html
<footer class="footer">

    <div class="footer-upper"></div>
    <nav class="row">
    <ul class=" navbar-nav col-md-4">
    <li class="nav-item">
    <a class="nav-link" href="{% url 'mainpage'%}">Rent It</a>
    </li>
    </ul>
    <ul class=" navbar-nav col-md-4">
    <li class="nav-item">
    <a class="nav-link" href="{% url 'contactus'%}">Contact</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="#">FAQ</a>
    <li class="nav-item">
    <a class="nav-link" href="#">Terms and Conditions</a>
    </li>
    </ul>
    <ul class=" navbar-nav col-md-4">
    <h3>Stay Connected</h3>
    <li class="nav-item">
    <a class="nav-link" target="_blank" href="https://twitter.com/ravensannex"><i class="fab fa-twitter fa-2x"></i></a>
    <a class="nav-link" target="_blank" href="https://www.facebook.com/"><i class="fab fa-facebook fa-2x"></i></a>
    <a class="nav-link" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram-square fa-2x"></i></a>
    </li>
    </ul>
    </nav>
    </div>
    <div class="footer-bottom text-center">
    <small>&copy; Copyright <script>const currentDate = new Date();
    document.write(currentDate.getFullYear());</script>, Stream Media. All Rights Reserved</small>
    </div>
    </footer>
    <!-- Footer -->

templates/head.html
{% load static %}
<title>{% block head_title%}Rental Property{% endblock head_title%}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" /> {% block extra_css%} {% endblock extra_css%}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
<link rel="stylesheet" href="{% static 'css/app.css' %}">

templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-primary" aria-label="Main Navigation">
    <a class="navbar-brand" href="{% url 'mainpage'%}">
        <img class="rounded float-left" src="{% static 'img/logop.png' %}" alt="Logo"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item"><a class="glyphicon glyphicon-home nav-link" href="{% url 'mainpage'%}">Home</a></li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'about-us'%}">
                    <i class="fas fa-info-circle"></i> About Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contactus'%}">
                    <i class="far fa-envelope"></i> Contact Us</a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-house-user"></i> Housing
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{%url 'housing:property-list'%}">All Housing</a>
                    <a class="dropdown-item" href="{%url 'housing:category-list'%}">Housing by Category</a> {% if user.is_authenticated %} {% if user.is_staff %}
                    <a class="dropdown-item" href="{%url 'housing:category-create'%}">Add Category</a>
                    <a class="dropdown-item" href="{%url 'housing:property-create'%}">Add Property</a>
                    <hr>




                </div>
            </li>
            {% endif %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout'%}">
                    <i class="fas fa-sign-out-alt"></i> Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:profile' user.username%}">
                    <i class="fas fa-user-circle"></i>{{request.user.username|capfirst}}'s profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'password_change'%}">
                    <i class="fas fa-edit"></i> Change Password</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register'%}">
                    <i class="fas fa-user-plus"></i> Register</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login'%}">
                    <i class="fas fa-sign-in-alt"></i> Login</a>
            </li>

            {% endif%}

        </ul>
    </div>
</nav>

templates/home_carousel.html
<div class="bd-example">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1" class=""></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2" class=""></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide" alt="First slide [800x400]" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22800%22%20height%3D%22400%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20800%20400%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_172f28157f0%20text%20%7B%20fill%3A%23555%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A40pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_172f28157f0%22%3E%3Crect%20width%3D%22800%22%20height%3D%22400%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22285.921875%22%20y%3D%22217.7%22%3EFirst%20slide%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
          <div class="carousel-caption d-none d-md-block">
            <h5>First slide label</h5>
            <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" data-src="holder.js/800x400?auto=yes&amp;bg=666&amp;fg=444&amp;text=Second slide" alt="Second slide [800x400]" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22800%22%20height%3D%22400%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20800%20400%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_172f28157f7%20text%20%7B%20fill%3A%23444%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A40pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_172f28157f7%22%3E%3Crect%20width%3D%22800%22%20height%3D%22400%22%20fill%3D%22%23666%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22247.3125%22%20y%3D%22217.7%22%3ESecond%20slide%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
          <div class="carousel-caption d-none d-md-block">
            <h5>Second slide label</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" data-src="holder.js/800x400?auto=yes&amp;bg=555&amp;fg=333&amp;text=Third slide" alt="Third slide [800x400]" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22800%22%20height%3D%22400%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20800%20400%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_172f28157f9%20text%20%7B%20fill%3A%23333%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A40pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_172f28157f9%22%3E%3Crect%20width%3D%22800%22%20height%3D%22400%22%20fill%3D%22%23555%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22277%22%20y%3D%22217.7%22%3EThird%20slide%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
          <div class="carousel-caption d-none d-md-block">
            <h5>Third slide label</h5>
            <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

templates/index.html
{% extends '_base.html'%} {% load static %} {{block.super}} | home {% block content%}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Find a housing that fits your need.</h1>
        {% include "home_carousel.html" %}
        <p>
            We are happy to help you find the housing. Contact us and let us what you need so we can assist in getting the housing that is affodable and convinient for you
        </p>
    </div>
</section>

<section class="container">
    <div class="row card-deck">
        <div class="col-md-4 card">
            <h2 class="text-center">All Housing</h2>
            <div class="card-body">
                <p class="card-text">Check out all available housing.</p>
                <a class="btn btn-outline-secondary" href="{%url 'housing:property-list'%}">View Housing</a>
            </div>
        </div>
        <div class="col-md-4 card">
            <h2 class="text-center">Latest listings</h2>
            <div class="card-body">
                <p class="card-text">Check out the newly posted housing.</p>
                <a class="btn btn-outline-secondary" href="{%url 'housing:property-list'%}">View latest</a>
            </div>
        </div>
        <div class="col-md-4 card">
            <h2 class="text-center">Other</h2>
            <div class="card-body">
                <p class="card-text">Other housing</p>
                <a class="btn btn-outline-secondary" href="{%url 'housing:property-list'%}">View Housing</a>
            </div>
        </div>
    </div>
    </div>
</section>


{% endblock content%}

templates/object_confirm_delete.html
{% extends '_base.html' %}
{% block title %}{{object_name}} Confirm delete?{% endblock %}
{% block content %}
<div class="row">
    <div class="card">
        
            <h1>Are you sure?</h1>
            <p>You're about to delete <strong>{{object.title}}</strong>. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <span class="btn-group">
                    <input class="btn btn-primary"
                    type="button" value="Cancel"
                    onclick='window.history.go(-1)'>
                    <input class="btn btn-danger" type="submit" value="Confirm"/>
                </span>
            </form>
        </div>
    </div>
{% endblock %}

templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page_obj.has_previous %}
			<a href="?page={{page_obj.previous_page_number}}">Prev</a>
			{%endif%}
			<span class="current">
				Page {{page_obj.number}} of {{paginator.num_pages}}.
			</span>
			{% if page_obj.has_next%}
				<a href="?page={{page_obj.next_page_number}}">Next</a>
			{% endif%}
		</span>
	</div>